language: scala
# run on new infrastructure
sudo: false

script:
  - git submodule update --init
  - cd dsp-framework; echo "Publishing the framework, this may take a while..."; ./update.bash; cd ..; make libs > /dev/null/; echo "Done updating!"
  - make travis
