language: scala
sudo: false

install:
  # Install Verilator (if not found in cache)
  # Get it from firrtl's install script
  - wget "https://raw.githubusercontent.com/ucb-bar/firrtl/master/.install_verilator.sh"
  - bash .install_verilator.sh

cache:
  directories:
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin

script:
  - git submodule update --init
  - cd dsp-framework; echo "Publishing the framework, this may take a while..."; ./update.bash; cd ..; make libs; echo "Done updating!"
  - make travis
